### PR TITLE
docs: fix readme AIP number

### PR DESCRIPTION
**Pull request by Nigui**
I made the error, no bounty thx.

### CODE REVIEW

**Comment by ghost** [comment]
@Nigui Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@Nigui A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@Nigui Your pull request has been merged and marked as tier 6. _It will earn you $1 USD._

**Pull request merged**
