### PR TITLE
AIP-25: Providing PoW like guarantees on (D)PoS networks

### PR DESCRIPTION
**Pull request by moazzamak**
This pull request submits an AIP that intends to provide longest chain and data immutability guarantees similar to PoW networks in a (D)PoS system.
Waiting for an AIP number to be assigned, will refactor again once that is done.

### CODE REVIEW

**Comment by kristjank** [comment]
can you set AIP-25

**Comment by moazzamak** [comment]
Refactored to the AIP number. I still need to add further clarification regarding transaction data and pseudocode in the specifications section which I will do later.

**Comment by moazzamak** [comment]
I have made the changes now. This should be ready to merge.

**Comment by moazzamak** [comment]
Also I was unsure with assigning new transaction type ids so I just chose 0xfe and 0xff at random. These can be changed if needed.

**Review by kristjank — APPROVED** [review]

**Pull request merged**
